### ISSUE TITLE
Link removal request

### ISSUE THREAD

**Issue by catfan** [shockerli/php-awesome#1]
Hello, the only official website of our Medoo project is https://medoo.in.

The link of http://medoo.lvtao.net is not our website, and it is out-of-date and full of translation error. Would you remove this please?

**Comment by shockerli** [comment]
> Hello, the only official website of our Medoo project is https://medoo.in.
> 
> The link of http://medoo.lvtao.net is not our website, and it is out-of-date and full of translation error. Would you remove this please?

Has modified.

**Comment by catfan** [comment]
Thanks.

However, why changed it to GitHub link, but not our official website link?
